version: "3"
services:
  client:
    build: .
    # ports:
    # - 3003:80

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=bridgert.duckdns.org
      - VALIDATION=duckdns
      - STAGING=true 
    volumes:
      - /home/bridger/data/swag:/config
    ports:
      - 3003:80
    restart: unless-stopped