version: "3"
services:
  client:
    build: .
    # ports:
    # - 3003:80

  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=bridgert.duckdns.org
      - VALIDATION=duckdns
      - STAGING=false 
    volumes:
      - /home/bridger/data/swag:/config
      - ./default.conf:/config/nginx/site-confs/default.conf 
    ports:
      - 0.0.0.0:3003:443
    restart: unless-stopped